---
kind: pipeline
type: kubernetes
name: freeswitch
service_account_name: drone-runner-aws-privileges

steps:
  - name: Compile Freeswitch AKA Banshee 
    image: ubuntu:22.04
    resources:
      limits:
        cpu: 2000
        memory: 4096MiB    
    commands:
      - /bin/bash freeswitch.sh

#  - name: Push to bucket
#    image: plugins/s3
#    settings:
#      bucket: ''
#      assume-role: 'arn:aws:iam::164490501968:role/prod/gulf/ziwo/k8s_core/drone-runner'
#      region: 'me-south-1'
