---
kind: pipeline
type: kubernetes
name: freeswitch
service_account_name: drone-runner-aws-privileges

steps:
  - name: Compile Freeswitch AKA Banshee 
    image: ubuntu:22.04
    resources:
      limits:
        cpu: 2000
        memory: 4096MiB    
    commands:
    - apk update && apk add git subversion build-essential autoconf automake libtool libncurses5 libncurses5-dev make libjpeg-dev libtool libtool-bin libsqlite3-dev libpcre3-dev libspeexdsp-dev libldns-dev libedit-dev yasm liblua5.2-dev libopus-dev cmake libtiff-dev  libcodec2-dev libcodec2-dev portaudio19-dev libmagickcore-dev libmp3lame-dev libmpg123-dev libshout3-dev libvlc-dev libpq-dev libmariadb-dev libldap2-dev erlang librabbitmq-dev libsmpp34-dev libyaml-dev libmongoc-dev libopencv-dev  libmemcached-dev libavformat-dev libh2o libh2o-dev libsoundtouch-dev libhiredis-dev signalwire-client-c libks libilbc-dev libbroadvoice-dev libsilk-dev libopus-dev libg7221-d autoconf automake devscripts  g++ gawk gettext libcurl4-openssl-dev libdb-dev libedit-dev libgdbm-dev libldns-dev libncurses5-dev libopus-dev libopus-ocaml libpcre3-dev libperl-dev libpq-dev libspeex-dev libspeexdsp-dev libssl-dev libtiff5-dev libtool libtool-bin libvorbis0a libogg0 libsqlite3-dev libogg-dev libvorbis-dev portaudio19-dev libshout3-dev libmpg123-dev libmp3lame-dev yasm libbsd-dev flite flite1-dev libflite1 liblua5.2-0 liblua5.2-dev lua5.2 luarocks
    - apk add  gcc-10 g++-10 cpp-10 && ln -s /usr/bin/gcc-10 /usr/bin/gcc && ln -s /usr/bin/g++-10 /usr/bin/g++
    - mkdir -p /opt/openssl && wget https://www.openssl.org/source/openssl-1.1.1q.tar.gz --no-check-certificate -P /opt/openssl/
    - tar -xzvf /opt/openssl/openssl-1.1.1q.tar.gz && cd /opt/openssl/openssl-1.1.1q && ./config && make install && cp /usr/local/bin/openssl /usr/bin/openssl
    - cd /opt  && git clone https://github.com/ASWATFZLLC/spandsp.git && cd spandsp && ./bootstrap.sh && ./bootstrap.sh && make && make install 
    - cd /opt  && git clone https://github.com/ASWATFZLLC/sofia-sip.git && cd sofia-sip && ./bootstrap.sh && ./bootstrap.sh && make && make install 
    - cd /opt  && git clone https://github.com/ASWATFZLLC/freeswitch.git -b v1.10.5.9 /opt/banshee
    - cd /opt  && git clone https://github.com/ASWATFZLLC/ziwo-ansible.git -b master /tmp/ziwo-ansible
    - cd /opt/banshee && ./bootstrap.sh -j
    - CFLAGS=-Wno-error ./configure --prefix=/usr/local/banshee --enable-core-pgsql-support --enable-zrtp
    - cp /tmp/ziwo-ansible/roles/debian9/banshee/files/freeswitch/modules.conf /opt/banshee/modules.conf
    - make


#  - name: Push to bucket
#    image: plugins/s3
#    settings:
#      bucket: ''
#      assume-role: 'arn:aws:iam::164490501968:role/prod/gulf/ziwo/k8s_core/drone-runner'
#      region: 'me-south-1'
